services:
  iscs-redis:
    container_name: iscs-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - 6379:6379

  iscs-worker:
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ./src:/iscs
    command: rq worker -u redis://iscs-redis:6379 default
    environment:
      REDIS_HOST: iscs-redis
    deploy:
      replicas: 3
    depends_on:
      - iscs-redis

  iscs-backend:
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ./src:/app
      - ./data:/data
    command: uvicorn main:app --port 9999 --reload --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: iscs-redis
    ports:
      - 9999:9999
#      - 9898:9898 # python debug server
    depends_on:
      - iscs-redis


  iscs-rq-dashboard:
    build:
      dockerfile: worker.Dockerfile
    command: rq-dashboard --redis-url=redis://iscs-redis:6379
    ports:
      - 9181:9181
#    profiles:
#      - dev
